name: Test and Release

on:
  push:
    branches: [master, dev]
    tags:
    - '*'
  pull_request:
    branches: [master, dev]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        pip install --upgrade pip setuptools
        pip install flake8 pre-commit==2.6.0
        pip install -r requirements.txt
    - name: Lint with flake8
      run: flake8 .
    - name: Lint with pre-commit
      run: script -e -c "pre-commit run --all-files"
    - name: Unit tests
      run: script -e -c "nosetests -v --rednose --nologcapture --nocapture tests"

  release:
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - uses: actions/checkout@v2
    - name: Install Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        pip install --upgrade pip setuptools
        pip install wheel twine
    - name: Build and publish to Pypi
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist
        twine upload dist/*
